spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:postgresql://localhost:5432/wedding
      username: root
      password: SorinSiRaluca
      hikari:
        auto-commit: true
        maximum-pool-size: 40
        minimum-idle: 20


  mail:
    host: smtp.gmail.com
    port: 587
    username: nuntasorinsiraluca@gmail.com
    password: lhomcfmixsoylqml
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: create

