#spring:
#  datasource:
#      url: jdbc:postgresql://localhost:5432/wedding
#      username: root
#      password: SorinSiRaluca

spring:
  datasource:
    url: jdbc:postgres://ebezhwdfpapvmd:cf682633e29fe08f169c5b97646b4904e4fa459134a64fdf246310ecaab41547@ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/dfppsfknbe62qq
    username: ebezhwdfpapvmd
    password: cf682633e29fe08f169c5b97646b4904e4fa459134a64fdf246310ecaab41547
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: nuntasorinsiraluca@gmail.com
    password: lhomcfmixsoylqml
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
